#pragma config(UserModel, "C:/Users/rstudent/code/robot-configs/35-Vector-VI.c")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include <CKVexIMEMotorSet.h>

task main()
{
	const tMotor mports[] = {mFlyTop, mFlyMidTop, mFlyMidBottom, mFlyBottom};


	IMEMotorSet motorset;
	IMEMotorSetInit( motorset, mports, 4, M393HighSpeed );

	setPower( motorset, 1.0 );
	while(1);
}
